### ISSUE TITLE
Endpoint for stacked bar chart

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/dlab-api#15]
Add support for front end to make get request to generate the visualization.

**Comment by meyersj** [comment]
As the number of possible values increase it maybe too much data to show users. We could include a user_id filter and only compute summaries on values that user ranked.

**Comment by meyersj** [comment]
Add better tests that will create users and some rankings and then verify response matches input.

**Comment by meyersj** [comment]
Make test case for when issue_id as a parameter doesn't actually exist in the graph.

**Comment by meyersj** [comment]
Closed by pull request #26
