### ISSUE TITLE
Adding get all values ranked by user for specific issue

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/dlab-api#17]

**Comment by meyersj** [comment]
Line 24: https://github.com/psu-capstone/dlab-api/blob/develop/app/mod_api/args.py

Keep arguments but include `user_id` as optional

Line 119: https://github.com/psu-capstone/dlab-api/blob/develop/app/mod_api/views.py

Check if `user_id` is passed as parameter and handle differently based on presence of `user_id`

Line 50: https://github.com/psu-capstone/dlab-api/blob/develop/app/mod_api/handlers.py

**Comment by meyersj** [comment]
@uym2 looks good

We should probably write some tests to make sure it all works properly. I just wrote some for the `graph.find_all()` method that you can use as a starting point. a178c2d9 has that code. It is currently in the `graph_tests` branch.

The test data is created in the `setUp` method.
- 1 `TestIssue` node
- 3 `TestValue` nodes
- Links from `TestIssue` node to the first two `TestValue` nodes

https://github.com/psu-capstone/dlab-api/blob/graph_tests/shared/neo_utils.py contains the convenience objects for creating test nodes and links.

For `graph.find_all_withUserId()` you will need to create a user, some test nodes and then rank them. You can then run tests to make sure you retrieve the correct data.
- `User` object
- `Node` objects
- ranks using the `Rank` object. 

We can tackle this on Tuesday together or you can get started and let me know if you have any questions.

**Comment by uym2** [comment]
Where can I find the methods assertIn and assertNotEqual?

**Comment by meyersj** [comment]
Inside the `unittest.TestCase` object you access call assert methods with `self.assertIn()` and `self.assertNotEqual()`.

See https://docs.python.org/2/library/unittest.html#unittest.TestCase for all possible assertion tests.
