### ISSUE TITLE
Use Neobox for safe test DB

### ISSUE THREAD

**Issue by midnightlynx** [psu-capstone/dlab-api#19]
http://py2neo.org/2.0/ext/neobox.html

We can use the Neobox extension to create/run a neo4j database for use in unit tests, to avoid the need to have a real neo4j instance already running somewhere in order for tests to pass.

**Comment by midnightlynx** [comment]
This also lets us test creation/ranking/mapping without risk of modifying real data somewhere.

**Comment by meyersj** [comment]
This looks pretty neat!

**Comment by midnightlynx** [comment]
PR submitted to implement.
