### ISSUE TITLE
Add endpoint for issue creation

### ISSUE THREAD

**Issue by meyersj** [psu-capstone/dlab-api#34]
Front end is working on interface for issue creation. Create an endpoint that accepts request with issue name, description and vectors containing value, objective and policy nodes. 

Backend logic should create new nodes for this issue and return a generated issue_id back to client.

**Comment by uym2** [comment]
@meyersj When do you need this to be done? I might be able to handle this (not today, but perhaps tomorrow or on weekend). It is great if you can add suggestions as starting points for me, ortherwise I will explore the code myself and ask for help later.

**Comment by meyersj** [comment]
@uym2 I don't think there is a big rush, but the front end has started putting together an interface. So it would be nice to start getting something ready for them.

I created a gist showing the expected format of the request. https://gist.github.com/meyersj/489dea14cc4f0f51b71e @ScienceRobot is implementing the UI so he can chime in if changes should be made to request format.  

Modifications that will be needed:
- Define the parameters in `args.py` using webargs. Looking at webargs documentation there is a `fields.List(..)` format that can be used for the nodes. http://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.List
- Add endpoint to `views.py` with POST method
- Create handler for the new endpoint in `handlers.py`
- Implement logic to create nodes and links in `graph.py` and return new `issue_id`

It would be awesome if you wanted to get started on this. Directions are fairly minimal so let me know if you need more information. Each node created will need a unique identifier generated. We can use the python `uuid` module for that.

**Comment by r-t-a** [comment]
the format looks fine by me, since the user is just going to submit it all at once and will most likely have multiple values, obj, policies attached to each issue.

**Comment by uym2** [comment]
I will leave the values, objectives, and policies as optional. Let me know if you want them to be required.

**Comment by m-d-s** [comment]
We're probably going to want to make them required so that each category has at least one item. We might also want to set a max, but that is something we can probably do on the front end

**Comment by meyersj** [comment]
@m-d-s @ScienceRobot 

This code is now live on `capdev`. You can create issues via a POST request to `api/issue` using the format below. If successful an `issue_id` will be returned.

```
  {
    issue_name:     <name string>,          // required
    desc:           <description string>,   // optional
    values:         [ <name string>, ... , <name string> ],
    objectives:     [ <name string>, ... , <name string> ],
    policies:       [ <name string>, ... , <name string> ]
  }
```

@uym2 Thanks for implementing this!

**Comment by m-d-s** [comment]
Great, we will start testing it as soon as possible

**Comment by r-t-a** [comment]
Awesome, thanks guys

**Comment by r-t-a** [comment]
@meyersj @uym2 I was doing some testing and noticed `issue_name`  is actually just `name` in the db, nothing wrong with that, just for documentation purposes thought I'd let you know.

**Comment by uym2** [comment]
I can fix that if you want to. Do you want to do the same for values/objectives/policies associated with it? Say, value_name, objective_name, policy_name?

**Comment by r-t-a** [comment]
I think it's fine how it is.
