### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/dlab-api#36]
Would it be possible to return the titles of the ranked items along with the stacked data? Right now we are looping and making a single request for each title after we have already gotten the stacked data. Is there any way we could avoid having to make those looping calls?

**Comment by meyersj** [comment]
Yea we can look into adding that.

**Comment by m-d-s** [comment]
Cool, thanks

**Comment by meyersj** [comment]
New structure of data for each node

```
node_id : {
  name: <node name>,
  data: [ SD count, D count, N count, A count, SA count ]
}
```

instead of

```
node_id : [ SD count, D count, N count, A count, SA count ]
```

**Comment by meyersj** [comment]
@m-d-s just pushed this change to `capdev`
